// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scripters.Regula.Platform.Shared.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace Scripters.Regula.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618162136_AddInventoryManagement")]
    partial class AddInventoryManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Scripters.Regula.Platform.CommercialManagement.Domain.Model.Aggregates.CommercialCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("ActiveDebtAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("active_debt_amount");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("DebtCount")
                        .HasColumnType("int")
                        .HasColumnName("debt_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_commercial_customers");

                    b.ToTable("commercial_customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveDebtAmount = 0m,
                            DebtCount = 0,
                            Name = "Cliente de prueba"
                        });
                });

            modelBuilder.Entity("Scripters.Regula.Platform.CommercialManagement.Domain.Model.Entities.CommercialDebt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("due_date");

                    b.Property<decimal>("RemainingAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("remaining_amount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_commercial_debts");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("i_x_commercial_debts_customer_id");

                    b.ToTable("commercial_debts", (string)null);
                });

            modelBuilder.Entity("Scripters.Regula.Platform.CommercialManagement.Domain.Model.Entities.CommercialDebtPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerDebtId")
                        .HasColumnType("int")
                        .HasColumnName("customer_debt_id");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("NewRemainingAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("new_remaining_amount");

                    b.Property<string>("Note")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("note");

                    b.Property<decimal>("PreviousRemainingAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("previous_remaining_amount");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_commercial_debt_payments");

                    b.HasIndex("CustomerDebtId")
                        .HasDatabaseName("i_x_commercial_debt_payments_customer_debt_id");

                    b.ToTable("commercial_debt_payments", (string)null);
                });

            modelBuilder.Entity("Scripters.Regula.Platform.DeliveryTracking.Domain.Model.Aggregates.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("DriverId")
                        .HasColumnType("int")
                        .HasColumnName("driver_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_deliveries");

                    b.ToTable("deliveries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DriverId = 101
                        });
                });

            modelBuilder.Entity("Scripters.Regula.Platform.DeliveryTracking.Domain.Model.Entities.DriverLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int")
                        .HasColumnName("delivery_id");

                    b.Property<int>("DriverId")
                        .HasColumnType("int")
                        .HasColumnName("driver_id");

                    b.Property<DateTime?>("Eta")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("eta");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_updated");

                    b.Property<double>("Latitude")
                        .HasColumnType("double")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double")
                        .HasColumnName("longitude");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_driver_locations");

                    b.HasIndex("DeliveryId")
                        .HasDatabaseName("i_x_driver_locations_delivery_id");

                    b.ToTable("driver_locations", (string)null);
                });

            modelBuilder.Entity("Scripters.Regula.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Scripters.Regula.Platform.InventoryManagement.Domain.Model.Aggregates.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("InventoryType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("inventory_type");

                    b.Property<long>("OwnerProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_profile_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_inventories");

                    b.HasIndex("OwnerProfileId", "InventoryType")
                        .IsUnique()
                        .HasDatabaseName("i_x_inventories_owner_profile_id_inventory_type");

                    b.ToTable("inventories", (string)null);
                });

            modelBuilder.Entity("Scripters.Regula.Platform.InventoryManagement.Domain.Model.Entities.GasCylinderStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Available")
                        .HasColumnType("int")
                        .HasColumnName("available");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("CylinderType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("cylinder_type");

                    b.Property<int>("InTransit")
                        .HasColumnType("int")
                        .HasColumnName("in_transit");

                    b.Property<int>("Observed")
                        .HasColumnType("int")
                        .HasColumnName("observed");

                    b.Property<int>("OutOfService")
                        .HasColumnType("int")
                        .HasColumnName("out_of_service");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int?>("inventory_id")
                        .HasColumnType("int")
                        .HasColumnName("inventory_id");

                    b.HasKey("Id")
                        .HasName("p_k_gas_cylinder_stocks");

                    b.HasIndex("inventory_id")
                        .HasDatabaseName("i_x_gas_cylinder_stocks_inventory_id");

                    b.ToTable("gas_cylinder_stocks", (string)null);
                });

            modelBuilder.Entity("Scripters.Regula.Platform.InventoryManagement.Domain.Model.Entities.Movement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("CylinderType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("cylinder_type");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("movement_type");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_id");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("provider_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int?>("inventory_id")
                        .HasColumnType("int")
                        .HasColumnName("inventory_id");

                    b.HasKey("Id")
                        .HasName("p_k_movements");

                    b.HasIndex("inventory_id")
                        .HasDatabaseName("i_x_movements_inventory_id");

                    b.ToTable("movements", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Scripters.Regula.Platform.InventoryManagement.Domain.Model.Entities.CompanyMovement", b =>
                {
                    b.HasBaseType("Scripters.Regula.Platform.InventoryManagement.Domain.Model.Entities.Movement");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("destination");

                    b.Property<string>("MovementReason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("movement_reason");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("observation");

                    b.ToTable("company_movements", (string)null);
                });

            modelBuilder.Entity("Scripters.Regula.Platform.InventoryManagement.Domain.Model.Entities.DistributorMovement", b =>
                {
                    b.HasBaseType("Scripters.Regula.Platform.InventoryManagement.Domain.Model.Entities.Movement");

                    b.Property<string>("OutboundType")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("outbound_type");

                    b.ToTable("distributor_movements", (string)null);
                });

            modelBuilder.Entity("Scripters.Regula.Platform.CommercialManagement.Domain.Model.Entities.CommercialDebt", b =>
                {
                    b.HasOne("Scripters.Regula.Platform.CommercialManagement.Domain.Model.Aggregates.CommercialCustomer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_commercial_debts_commercial_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Scripters.Regula.Platform.CommercialManagement.Domain.Model.Entities.CommercialDebtPayment", b =>
                {
                    b.HasOne("Scripters.Regula.Platform.CommercialManagement.Domain.Model.Entities.CommercialDebt", "CustomerDebt")
                        .WithMany()
                        .HasForeignKey("CustomerDebtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_commercial_debt_payments_commercial_debts_customer_debt_id");

                    b.Navigation("CustomerDebt");
                });

            modelBuilder.Entity("Scripters.Regula.Platform.DeliveryTracking.Domain.Model.Entities.DriverLocation", b =>
                {
                    b.HasOne("Scripters.Regula.Platform.DeliveryTracking.Domain.Model.Aggregates.Delivery", "Delivery")
                        .WithMany()
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_driver_locations_deliveries_delivery_id");

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("Scripters.Regula.Platform.InventoryManagement.Domain.Model.Entities.GasCylinderStock", b =>
                {
                    b.HasOne("Scripters.Regula.Platform.InventoryManagement.Domain.Model.Aggregates.Inventory", null)
                        .WithMany("StockItems")
                        .HasForeignKey("inventory_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("f_k_gas_cylinder_stocks_inventories_inventory_id");
                });

            modelBuilder.Entity("Scripters.Regula.Platform.InventoryManagement.Domain.Model.Entities.Movement", b =>
                {
                    b.HasOne("Scripters.Regula.Platform.InventoryManagement.Domain.Model.Aggregates.Inventory", null)
                        .WithMany("Movements")
                        .HasForeignKey("inventory_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("f_k_movements_inventories_inventory_id");
                });

            modelBuilder.Entity("Scripters.Regula.Platform.InventoryManagement.Domain.Model.Entities.CompanyMovement", b =>
                {
                    b.HasOne("Scripters.Regula.Platform.InventoryManagement.Domain.Model.Entities.Movement", null)
                        .WithOne()
                        .HasForeignKey("Scripters.Regula.Platform.InventoryManagement.Domain.Model.Entities.CompanyMovement", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scripters.Regula.Platform.InventoryManagement.Domain.Model.Entities.DistributorMovement", b =>
                {
                    b.HasOne("Scripters.Regula.Platform.InventoryManagement.Domain.Model.Entities.Movement", null)
                        .WithOne()
                        .HasForeignKey("Scripters.Regula.Platform.InventoryManagement.Domain.Model.Entities.DistributorMovement", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scripters.Regula.Platform.InventoryManagement.Domain.Model.Aggregates.Inventory", b =>
                {
                    b.Navigation("Movements");

                    b.Navigation("StockItems");
                });
#pragma warning restore 612, 618
        }
    }
}
